import Logo from "../../public/assets/svg/darklogo.svg";
import Image from "next/image";
import { useState, useEffect } from "react";
import brands from "../../public/assets/img/brands.svg";
import Head from "next/head";

function Portfolio() {
  const [activeTab, setActiveTab] = useState("Photos");
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);

  return (
    <div>
      <Head>
        <title>Our Clients</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/mklogo.svg" />
      </Head>
      <div className="bg-[#ECE7DC] px-16 -mt-4 pb-8 min-h-screen">
        {/* Logo */}
        <Image src={Logo} />
        <main>
          <p class="text-5xl text-center font-medium -mt-[20px] text-neutral-900">
            Clients
          </p>
          {/* Clients */}
          <div className="w-full grid place-content-center mt-20">
            <Image src={brands} />{" "}
          </div>
        </main>
      </div>
    </div>
  );
}

export default Portfolio;
