import Logo from "../../public/assets/svg/darklogo.svg";
import Image from "next/image";
import brands from "../../public/assets/img/brands.svg";
import Head from "next/head";

function Portfolio() {

  return (
    <div>
      <Head>
        <title>Our Clients</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/mklogo.svg" />
      </Head>
      <div className="bg-[#ECE7DC] px-8 lg:px-16 -mt-4 pb-8 min-h-screen">
        {/* Logo */}
        <Image priority src={Logo} alt="clients" className="w-auto h-auto" />
        <main>
          <p className="lg:text-5xl text-4xl text-center font-medium mt-8 lg:-mt-[20px] text-neutral-900">
            Clients
          </p>
          {/* Clients */}
          <div className="w-full grid place-content-center mt-20">
            <Image priority src={brands} alt="brands" />{" "}
          </div>
        </main>
      </div>
    </div>
  );
}

export default Portfolio;
